### ISSUE TITLE
Avoid masterfile access on every query

### ISSUE THREAD

**Issue by gra-moore** [BrightstarDB/BrightstarDB#115]
Profiling query performance I noted the following:

public ISerializationFormat Query(string storeName, string queryExpression, IEnumerable<string> defaultGraphUris,
                                          DateTime? ifNotModifiedSince,
                                          SparqlResultsFormat sparqlResultFormat, RdfFormat graphFormat,
                                          Stream responseStream)
        {
            Logging.LogDebug("Query {0} {1}", storeName, queryExpression);
            var commitPoint =
                _storeManager.GetMasterFile(Path.Combine(_baseLocation, storeName)).GetCommitPoints().First();

The commit point lookup was 32% of this method call. The actual query only 23%. Parsing was the next worse thing.

We should look to keep commit point info in memory so that it can be accessed by queries.

**Comment by kal** [comment]
I just profiled this with the current code-base and in the profiling the GetMasterFile call is consistently coming in at less than 2% of overall query time, not the 32% you are seeing. 

I guess that this may depend a bit on the relative size of the master file and main data file and whether or not the OS file cache is working in your favour; and also on how complicated the actual query itself is. My guess is that if you are doing lots of relatively small queries on a store that is quite big and has a lot of commits you may see master file access become an issue because opening the master file reads a block from the start of the file, and then accessing the last commit point reads a block from the end.

To help this I've made some changes so that now the BPlusTreeStoreManager maintains a cache of MasterFile objects and those object in turn contain a cache of accessed commit points. This should mean that we don't need to constantly reread the header block on the master file and between updates we should be able to read the last commit point from the cache without having to seek or read data.
