### ISSUE TITLE
Looking up entities with spaces in IDs fails in unexpected way

### ISSUE THREAD

**Issue by kentcb** [BrightstarDB/BrightstarDB#175]
Entities with spaces in their IDs save just fine, but attempting to find them fails:

```C#
[Entity]
public interface IEntity
{
    [Identifier]
    string Id
    {
        get;
    }
}

class Program
{
    static void Main(string[] args)
    {
        var connectionString = "type=embedded;storesdirectory=Stores;storename=Repro";
        var client = BrightstarService.GetClient(connectionString);

        if (client.DoesStoreExist("Repro"))
        {
            client.DeleteStore("Repro");
        }

        // this works
        string id = "ref1";

        // this does not work
        //string id = "ref 1";

        using (var context = new MyEntityContext(connectionString))
        {
            context.Entities.Add(new Entity { Id = id });
            context.SaveChanges();
        }

        using (var context = new MyEntityContext(connectionString))
        {
            var entity = context
                .Entities
                .Where(x => x.Id == id)
                .FirstOrDefault();

            Console.WriteLine(entity == null ? "NOT FOUND" : "FOUND");
        }

        Console.WriteLine("DONE");
        Console.ReadKey();
    }
}
```
The entity is clearly present in the context and it has the correct ID, but the `Where` clause fails to find it if it contains a space.

**Comment by kal** [comment]
This sounds like a bug probably in some conversion/URI escaping code somewhere.

**Comment by kal** [comment]
This looks like an issue with the DNR SPARQL parser - the IRI for the entity in the query is having the space removed so:
```
ASK { <http://www.brightstardb.com/.well-known/genid/ref 1> a <http://example.com/entity> . }
```
before parsing becomes
```
ASK { <http://www.brightstardb.com/.well-known/genid/ref1> a <http://example.com/entity> . }
```
after parsing and so doesn't match the triples already added to the store.

**Comment by rvesse** [comment]
Well spaces are invalid in URIs anyway

But if you can reproduce the issue with the parser I will take a look

**Comment by kal** [comment]
Are spaces not supposed to be unescaped in SPARQL queries ? or should it be:

```
ASK { <http://www.brightstardb.com/.well-known/genid/ref%201> a <http://example.com/entity> . }
```

This looks wrong to me as it is then impossible to tell if the % has been escaped or not...

**Comment by rvesse** [comment]
Well since spaces are illegal they must be escaped as `%20`, it is possible that the parser is a little lax in this regard

It's also worth noting that in .Net `Uri.ToString()` and `Uri.AbsoluteUri` can yield different values, the `ToString()` form will unescape some things (such as `%20`) whereas the `AbsoluteUri` provides a more canonical representation of a URI

If you create a URI with a space programmatically I think .Net internally escapes it to `%20` for you

**Comment by kal** [comment]
Yep, you are right of course :) SPARQL has its own IRIREF production which excludes the space character, but then also says that the string after SPARQL-defined unescaping must conform to the [relevant RFC](http://www.ietf.org/rfc/rfc3987.txt). And in there it says (as I read it) that space should be % encoded as it is not in either the unreserved or ucschar productions.

I think the problem with the .NET URI constructor is that it will escape chars that are valid in an IRI unless you hack around with your app config file or create a custom GenericUriParser. I'm not sure if that will cause a problem because a character like LATIN SMALL LETTER I WITH ACUTE (í) is totally legal in an IRI but in a URI must be escaped as appears in its %C3%AD (two separate UTF-8 bytes). I guess I need to suck it and see, but it would be nice if there was a clear answer on this somewhere.

So it looks like the root cause is that B* needs to ensure that the IRI identity generated for an entity follows the rules on escaping. There is (in my mind) an open question about whether the .NET URI class provides suitable escaping. 

There is also a (lesser) problem that the DNR SPARQL parser is silently dropping the invalid space character rather than reporting a error. I'll see if I can create a simple repro for that at least.

**Comment by rvesse** [comment]
Yes also the behaviour changes depending on the version of the framework and how it is configured.  

IRI parsing rules can be enabled for any .Net version from 2.0 onwards but are incomplete.  From .Net 4.5 onwards they obey the specs properly and are on by default

**Comment by kal** [comment]
Code is now changed to ensure the generated identifiers are escaped using .NET's Uri.EscapeUriString(). The Id is still provided back through the entity in its unescaped form, so an entity with Id property "some string" might have a URI like <http://example.org/id/some%20string>, but this occurs transparently to code using the EF.

**Comment by filippobottega** [comment]
If the Id property is mapped to a property that contains a value like "some string" I get the exception:

Si è verificata l'eccezione VDS.RDF.Parsing.RdfParseException
  HResult=0x80131500
  Messaggio=[Line 1 Column 101] Illegal white space in URI '<http://www.brightstardb.com/.well-known/genid/some'
  Origine=dotNetRDF
  Analisi dello stack:
   in VDS.RDF.Parsing.Tokens.SparqlTokeniser.TryGetUri()
   in VDS.RDF.Parsing.Tokens.SparqlTokeniser.GetNextToken()
   in VDS.RDF.Parsing.Tokens.TokenQueue.InitialiseBuffer()
   in VDS.RDF.Parsing.SparqlQueryParser.ParseInternal(SparqlQueryParserContext context)
   in VDS.RDF.Parsing.SparqlQueryParser.ParseInternal(TextReader input)
   in VDS.RDF.Parsing.SparqlQueryParser.ParseFromString(String queryString)
   in BrightstarDB.Server.ServerCore.ParseSparql(String exp)
   in BrightstarDB.Server.ServerCore.Query(String storeName, String queryExpression, IEnumerable`1 defaultGraphUris, Nullable`1 ifNotModifiedSince, SparqlResultsFormat sparqlResultFormat, RdfFormat graphFormat, Stream responseStream)
   in BrightstarDB.Client.EmbeddedDataObjectStore.ExecuteSparql(SparqlQueryContext sparqlQueryContext)
   in BrightstarDB.Client.DataObjectStoreBase.ExecuteSparql(String sparqlQuery)
   in BrightstarDB.Client.DataObjectStoreBase.GetReferencingTriples(String identity)
   in BrightstarDB.Client.DataObjectStoreBase.GetReferencingTriples(IDataObject obj)
   in BrightstarDB.Client.DataObject.UpdateIdentity(String newIdentity, Boolean enforceClassUniqueConstraint)
   in BrightstarDB.EntityFramework.BrightstarEntityObject.set_Identity(String value)
   in BrightstarDB.EntityFramework.BrightstarEntityObject.SetKey(String key)
   in BrightstarDB.EntityFramework.BrightstarEntityObject.OnPropertyChanged(String propertyName)
   in BrightstarDB.EntityFramework.BrightstarEntityObject.SetRelatedProperty(String propertyName, Object value)

  I suppose that the problem is in method:

public void Attach(EntityContext context, bool overwriteExisting = false)

  of class BrightstarEntityObject at line:

this.DataObject = this._context.GetDataObject(new Uri(this._identity), false);

  because if this._identity is equal to "some%20string", the Uri.ToString is equal to "some string" in function this._context.GetDataObject(...).

  For this reason this.DataObject is build with a unescaped string.

  Regards,
    Filippo.
