### ISSUE TITLE
The dependency on Portable.Runtime causes type duplication issues

### ISSUE THREAD

**Issue by kentcb** [BrightstarDB/BrightstarDB#178]
When using B* from iOS, the types in Portable.Runtime duplicate those in the standard library. Thus, if one uses a type such as `System.Diagnostics.Stopwatch` you get an error:
```
The imported type ‘System.Diagnostics.Stopwatch’ is defined multiple times
```
To get around this, I just remove the reference to Portable.Runtime. However, I'm guessing it's possible to drop this dependency altogether for iOS?

**Comment by kal** [comment]
I'll have to check this - I have a feeling that even under iOS there is some need for Portable.Runtime, but if its not needed then the reference can be dropped. I'm guessing that when you remove the reference stuff carries on working so that's a strong indication that its not really needed for iOS.

**Comment by kal** [comment]
After further investigation, Portable.Runtime is a reference included by the dotNetRDF nuget package, so its not going to be possible to remove it without changes to the upstream package.

**Comment by rvesse** [comment]
@kal Historically you were the one who introduced `Portable.Runtime` as a reference in the dotNetRDF portable packages.

If this is no longer necessary or causing an issue feel free to try and fix this in dotNetRDF

**Comment by kal** [comment]
I think the issue is that it is required for compatibility with some of the platforms, but possibly not for others. Xamarin.iOS is a platform that post-dates the implementation work I did in DNR. I'll see if I can get something sorted out for the next DNR release - it will probably involve some changes to the target profile(s) for DNR though.

**Comment by rvesse** [comment]
Peter Kahle already has a pull request open to upgrade the PCL profile - https://bitbucket.org/dotnetrdf/dotnetrdf/pull-request/32/core-429/diff - so if you could review that since you might understand if it is the right upgrade to make or not and use that as a starting point it would be helpful.

Honestly the whole PCL profiles thing is a horrific mess and every time I have to go near it I want to kill the people at Microsoft who thought it was a good idea

**Comment by kal** [comment]
I feel your PCL-profile-related pain, believe me!

It looks like Peter's pull request is along the correct lines but it omits the Xamarin.iOS target. I'll see if I can pull something together and test locally. I could take a look at vds-common as well if that would help?

**Comment by rvesse** [comment]
Yes that would be much appreciated
