### ISSUE TITLE
Platform library stripped unless code explicitly uses it

### ISSUE THREAD

**Issue by kentcb** [BrightstarDB/BrightstarDB#181]
Running on iOS, the platform library (BrightstarDB.Portable.iOS) is stripped out of the built code because nothing explicitly uses it. To that end, I had to add this class to my code:
```C#
using BrightstarDB;

// needed because otherwise nothing refers to anything within the platform lib and it therefore gets stripped out
public static class ForceReference
{
    static ForceReference()
    {
        ConfigurationProvider dummy = null;
    }
}
```
I've seen other libraries deal with this in a similar fashion. Perhaps code akin to this could be added to the NuGet package?

**Comment by kal** [comment]
OK, I'll update it to do that - it didn't used to happen with MonoTouch...

**Comment by kal** [comment]
Due to limitations of the nuget packaging this reference fill will be included in all projects that use the BrightstarDB.Platform NuGet package, but I can't see it being harmful for Android/WP apps in any way (and the developer always has the option of deleting or excluding the source file from their project if it does clash).
