### ISSUE TITLE
OrderBy filters null values

### ISSUE THREAD

**Issue by kentcb** [BrightstarDB/BrightstarDB#186]
An `OrderBy` invocation is filtering out those entities that have `null` for the value of the ordered property. Example code:
```C#
[Entity]
public interface IEntity
{
    string Id
    {
        get;
    }

    string Property
    {
        get;
        set;
    }
}

using (var context = new MyEntityContext(connectionString))
{
    var entity = context.Entities.Create();
    entity.Property = "a";
    entity = context.Entities.Create();
    entity.Property = null;
    entity = context.Entities.Create();
    entity.Property = "c";
    context.SaveChanges();
}

using (var context = new MyEntityContext(connectionString))
{
    var ordered = context
        .Entities
        .OrderBy(x => x.Property)
        .ToList();

    foreach (var item in ordered)
    {
        Console.WriteLine("{0} : {1}", item.Id, item.Property);
    }
}
```
Sample output:
```
c65d08ad-8df2-45ea-bbef-bbee5305bd20 : a
11fd3908-2211-42de-85a3-2252373bbb75 : c
DONE
```
The entity with `Property == null` is filtered out instead of appearing first in the list as I would have expected.

**Comment by kal** [comment]
Ah, that is because in the underlying store the entity doesn't have a property at all. When a property is set to null there is nothing in the store. This is really in the nature of using a triple store underneath the entity framework. In this case, if you actually want all of the entities then I would do the sort on the list returned by the LINQ query:
```(c#)
var all = context context.Entities.ToList();
foreach(var item in all.OrderBy(x=>x.Property) {
   ...
}
```

If you really want to page the items rather than pull them all out then I would recommend that you decide if NULL sorts high or low and then factor in a separate query to find those that does the query for Property==NULL before (or after) the ordered query.

**Comment by kal** [comment]
This would be worth adding to the EF docs
