### ISSUE TITLE
Querying for a set of entities given their IDs

### ISSUE THREAD

**Issue by kentcb** [BrightstarDB/BrightstarDB#190]
Hi,

I hope it's OK to ask a question here - always feels a bit odd to me asking a question via an issue.

Assuming I have a set of entity IDs, is there a recommended approach to querying for those entities? Naturally I could just loop over them and query one-by-one, but I was hoping for something more efficient akin to this SQL:
```SQL
select * from foo
where id IN [1,2,3,4,5]
```

**Comment by kal** [comment]
Currently our support for .Contains() is for literal values only (i.e. specifically not IDs) - see http://brightstardb.readthedocs.org/en/latest/Entity_Framework/#supported-linq-operators

However, I can see that in some cases this would be useful - especially because it would save some roundtrips in client-server setups. It might be possible to extend the LINQ to SPARQL processor to specifically support the use-case of `context.Foos.Where(x=>['1', '2', '3', '4', '5'].Contains(x.Id))`. I'll log this as an enhancement request.

**Comment by kal** [comment]
I've added code for supporting a query of the form:

```
context.Foos.Where(x=>new []{'1', '2', '3'}.Contains(x.Id))
```
This would be similar to a SQL query like:
```
SELECT * from foo where id in [1,2,3]
```

I have a couple of basic unit tests in there (one to test the generated SPARQL and one to validate that the results of the query are what would be expected). If you hit any problems with it - let me know.
