### ISSUE TITLE
Creating an entity and assigning ID throws if no context has previously been created

### ISSUE THREAD

**Issue by kentcb** [BrightstarDB/BrightstarDB#191]
Hi,

The following code fails with a `NullReferenceException`:
```C#
[Entity]
public interface IEntity
{
    string Id
    {
        get;
    }
}

static void Main(string[] args)
{
    var connectionString = "type=embedded;storesdirectory=Stores;storename=Repro";
    //var dummy = new MyEntityContext(connectionString);

    var entity = new Entity
    {
        Id = "foo"
    };

    Console.WriteLine("DONE");
    Console.ReadKey();
}
```
Uncommenting the `dummy` local avoids the exception. Here is the exception trace:
```
System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=BrightstarDB
  StackTrace:
       at BrightstarDB.EntityFramework.BrightstarEntityObject.GetIdentityBase()
       at BrightstarDB.EntityFramework.BrightstarEntityObject.SetKey(String key)
       at BrightstarDB_REPRO.Entity.set_Id(String value) in \\psf\home\Documents\Visual Studio 2013\Projects\BrightstarDB_REPRO\MyEntityContext.cs:line 121
<snip>
```
This came up in testing. I was creating some entities before converting them to my contract type (I already have the helpers to do that so wanted to leverage them), but found that I was getting this exception.

**Comment by kal** [comment]
Thanks for the report. I'll take a look into this.

**Comment by kal** [comment]
This is happening because creating the static constructor on the context class initialises a mapping cache that the entity code is relying on. I've modified the text template so that the method that does this is now exposed as a public static method. So you can make your tests work by inserting:

```
MyEntityContext.InitializeEntityMappingStore();
```

before any code that creates entities. This essentially allows you to construct the cache of reflection information without the overhead of creating the context itself. 
NOTE: in normal operation the static constructor of the context class will invoke this method so you won't need to (and probably shouldn't) call this method in your normal application code.
