### ISSUE TITLE
Updating entity with composite key is problematic

### ISSUE THREAD

**Issue by kentcb** [BrightstarDB/BrightstarDB#192]
This is tangential to #189. I'm finding it difficult to take the same approach with composite key entities. Here's some example code:
```C#
[Entity]
public interface IParentEntity
{
    [Identifier("http://example.org/repro/")]
    string Id
    {
        get;
    }

    ICollection<IChildEntity> Children
    {
        get;
        set;
    }
}

[Entity]
public interface IChildEntity
{
    [Identifier("http://example.org/repro/", KeyProperties = new[] { "Parent", "Code" })]
    string Id
    {
        get;
    }

    string Code
    {
        get;
        set;
    }

    string Description
    {
        get;
        set;
    }

    [InverseProperty("Children")]
    IParentEntity Parent
    {
        get;
        set;
    }
}

using (var context = new MyEntityContext(connectionString))
{
    var parent = context.ParentEntities.Create();
    var child = context.ChildEntities.Create();
    child.Code = "child";
    child.Description = "Some description";
    child.Parent = parent;
    context.ChildEntities.Add(child);

    context.SaveChanges();
}

using (var context = new MyEntityContext(connectionString))
{
    var parent = context.ParentEntities.First();
    var child = context.ChildEntities.First();

    child.Description = "Update description";

    context.SaveChanges();
}
```
This results in an exception in the second call to `SaveChanges()`:
```
BrightstarDB.EntityFramework.EntityKeyChangedException was unhandled
  HResult=-2146233088
  Message=The entity's key properties have been modified without updating the identity value.
  Source=BrightstarDB
  StackTrace:
       at BrightstarDB.EntityFramework.BrightstarEntityContext.EnsureIdentity(IEntityObject item)
       at BrightstarDB.EntityFramework.BrightstarEntityContext.EnsureIdentity()
       at BrightstarDB.EntityFramework.BrightstarEntityContext.SaveChanges()
<snip>
```
I also ran into a bunch of other issues just getting the repro to this point, including:
* I *had* to use the `Create()` method to create the child entity (I couldn't just new it up as you'd expect)
* I *had* to set `Parent` on the child rather than adding the child to the parent's `Children` collection. This *might* be related to #184 but I got a different exception this time, so not convinced

**Comment by kal** [comment]
This is happening because your composite key includes an inverse property. Inverse properties are not loaded by default when you retrieve an entity - they are instead lazily loaded when you ask for the property value. The problem is that the code that constructs the identifier doesn't trigger the lazy loading. It would probably be good if it did, so this is a bug. But even if it did that means you always end up loading that inverse relationship during a SaveChanges because the identifier is always recomputed and validated.

So my recommendation would be to swap things so that the [InverseProperty] is on IParentEntity.Children. This will (a) work around the bug for now and (b) be more efficient anyway once the bug is fixed.

**Comment by kentcb** [comment]
Thanks Kal - just tried your suggestion and can confirm that it works in my repro. I'm getting a different error in my real project now, but will look into that separately.

It would be pure awesome sauce if the t4 template issued an appropriate warning if it detects the scenario where a composite key is specified on a lazy-loaded property.

**Comment by kal** [comment]
I've changed the code now so that identity changes are handled much better. It should update references to the entity that has changed identity both locally and in the store.
However, I have not currently implemented any notion of "cascading" identity changes down to other entities that have an identity that depends on the identity of the modified entity.
