### ISSUE TITLE
Setup: System.Web.Razor.dll should be deployed

### ISSUE THREAD

**Issue by Lercher** [BrightstarDB/BrightstarDB#206]
Symptom: http status 500 by Nancy when accessing localhost:8090/brightstar after insatallation on a "clean" box.

Cause: Nancy.ViewEngines.Razor.dll depends on System.Web.Razor.dll. If MVC (or Visual Studio) is not installed on the box, it cannot be found in the GAC/native image cache.

Proposed solution: The dll and its dependencies should be added to BrightstarDB\Webapp\bin and BrightstarDB\Service or the GAC by the installer. Please see the discussion in https://brightstardb.codeplex.com/discussions/573342 for more detail.

Martin

**Comment by kal** [comment]
Thanks for the bug report! 

This looks like it is actually a problem with the way the web.config file is written for the BrightstarDB server. Nancy's Razor implementation is independent of Microsoft's, but the configuration section in web.config is referencing the MS Razor DLL. I think it is just a question of either rewriting this or replacing the web.config-based configuration of Nancy's Razor view engine with a code-based configuration as described here: https://github.com/NancyFx/Nancy/wiki/Razor-View-Engine.

I'll take a look and see if I can remove the dependency on MS's Razor - if not then as you say we should ship it with the installer.

**Comment by Lercher** [comment]
Hi Kal,

I'm afraid to say that I am not quite convinced. I just checked with ildasm's Manifest viewer that Nancy's razor view has indeed an explicit external Dll reference to system.web.razor, so imho it's useless to fiddle with the config files. But I'm not really familiar with Nancy, probably they have just forgotten to remove the formal reference.

Mit freundlichen Grüßen,
Martin Lercher

Am 17.05.2015 um 16:11 schrieb Kal Ahmed <notifications@github.com>:

Thanks for the bug report!

This looks like it is actually a problem with the way the web.config file is written for the BrightstarDB server. Nancy's Razor implementation is independent of Microsoft's, but the configuration section in web.config is referencing the MS Razor DLL. I think it is just a question of either rewriting this or replacing the web.config-based configuration of Nancy's Razor view engine with a code-based configuration as described here: https://github.com/NancyFx/Nancy/wiki/Razor-View-Engine.

I'll take a look and see if I can remove the dependency on MS's Razor - if not then as you say we should ship it with the installer.

**Comment by kal** [comment]
I hope that is not the case! I'm just setting up a test VM now (a vanilla Server 2012 install) that I can try this out on. 

Anyway, if it turns out that MS's Razor is needed, I think we are OK to redistribute it under the Apache license, but I'll need to double check, or alternatively we could just document it as a pre-requisite.

**Comment by kal** [comment]
OK, it looks like you are right - even though their docs say that it is separate and that it can be configured without reference to the MS assembly, there is obviously some sort of dependency in there and it is causing the server to die unless the MS Razor assembly is included.

I've commited a fix to the installer build that ensures that razor does get copied into the installer. But I've also opened #207 because I would really like to sort this mess out by just dropping Razor from the server - it doesn't really provide much values over Nancy's SSVE for our purposes, and dropping it would remove not only MS's Razor but also Nancy's Razor plugin as dependencies.
