### ISSUE TITLE
Documentation: wildcard URI et. al. in the RDF client API

### ISSUE THREAD

**Issue by Lercher** [BrightstarDB/BrightstarDB#217]
Hi,

It would be nice, if you could extend the RDF Client API a bit: as there is no separate topic for the sparql rest service I falsely thought, it could be used for that. So I suggest:

(1) there should be a note that the rdf client api is not just a simple .net language wrapper around sparql but extends the language in some cases.

(2) at http://brightstardb.readthedocs.org/en/latest/RDF_Client_API/#deleting-data there should be a note, that the wildcard uri is such a feature of the client API.

(3) probably applies to other extensions to the language, I'm not aware of.

**Background**

I was wondering why the rest service wouldn't delete the nodes in the following update with the wildcard from the rdf client API (I have a different method that works with standard update):

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://www.brightstardb.com/example/article#>
DELETE DATA {
  <http://www.brightstardb.com/example/article/1433424821849> a <http://www.brightstardb.com/.well-known/model/wildcard> ; rdf:Bag <http://www.brightstardb.com/.well-known/model/wildcard> ;
    :tags <http://www.brightstardb.com/.well-known/model/wildcard> ;  :md <http://www.brightstardb.com/.well-known/model/wildcard> ;  :title <http://www.brightstardb.com/.well-known/model/wildcard> ;  :abstr <http://www.brightstardb.com/.well-known/model/wildcard> .
} ;
INSERT DATA {
  <http://www.brightstardb.com/example/article/1433424821849> a <http://www.brightstardb.com/example/article/> ;
    rdf:Bag :tags ;
    :tags "Kid" ;
    :tags "New" ;
    :md "" ;
    :title "A New Kid on the Block" ;
    :abstr "there are new kids everywhere, so the probability that one is new on the block is not zero." .
}
```

and tracked it down to src\core\BrightstarDB\Server\DeletePatternSink.cs implementing wildcards with an internal query followed by a delete loop. But this method never gets called. Instead the REST service seems to use the dotnetRDF standard implementation via src\core\BrightstarDB\Update\BrightstarUpdateProcessor.cs which knows nothing about wildcards.

Maybe this _store.DeleteTriple(t); loop leads to several/lots of roundtrips if you use a remote store connection? Did you consider to override the DeleteCommand behavior inside ProcessCommand() in BrightstarUpdateProcessor to handle wildcards there? I'm really new to the code and don't understand anything, so excuse me if these are dumb questions.

**Comment by kal** [comment]
Hi Martin,

I think the solution of extending the update processor so that the wildcard URI is supported in there is a good idea. I'll have to take a look at how feasible it is, but I think it shouldn't be too hard to implement.

Either way the docs do need extending in this area to make it more clear what is and what isn't possible with the APIs. As a start on documenting the REST APIs I've already created a swagger spec - its not comprehensive because Swagger is quite opinionated about the form of APIs and not all W3C recommendations follow the same opinions, but it is a useful start at least. However there should still be more in the docs, with pointers to the relevant W3C documents (which are mostly pretty readable) and we should definitely call out the special case of the wildcard URI. Even if we end up adding support for it into our SPARQL update implementation, that should still be called out as it is an extension to the SPARQL Update recommendation.

Cheers

Kal

**Comment by kal** [comment]
Enhancement: Add support for using the wildcard URI in the DELETE clause (or DELETE DATA clause) of a SPARQL Update command.

Documentation: Add some documentation on the REST API, including pointers to the relevant recommendations and notes on where we extend them. Also document our other proprietary REST APIs - the swagger docs might be a good place to start for this.

**Comment by kal** [comment]
I'm going to split this into two separate issues. This issue will be kept to track the request to add support for wildcard matches in SPARQL Update DELETE / DELETE DATA clauses. #220 has been created to track the request for documentation of our HTTP APIs

**Comment by kal** [comment]
I've implemented to additional support for wildcards in the DELETE and DELETE DATA commands - there are some unit tests, but if you get chance to try this out in your code that would be great.

As I've moved the issue about documentation to #220, I'm going to close this issue.
