### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by vba** [BrightstarDB/BrightstarDB#218]
Greetings,

I would like to know how fast is BrightstarDB. Could we compare its performances to those of mysql or mongodb. Any kind of comparison will be welcome. Many thanks.

**Comment by kal** [comment]
Hi,
Its kind of difficult to give a meaningful performance comparison - a lot depends on the particular profile of the application and what your requirements are. BrightstarDB is transactional (like mysql); but it supports variablility in the shape of data you store (like mongo); it is a graph database rather than a relational DB or key-value store, so it also has different performance characteristics from either of those other database technologies.

I don't have any performance statistics for BrightstarDB at the moment - I'd be really happy if someone would like to take on the work of doing some basic benchmarking of the store though. If anyone wants to take this on, please comment on this issue and we can discuss what sort of benchmarking scenarios would be good to run.

Cheers

Kal
