### ISSUE TITLE
Inserting only new triples by BrightstarDB

### ISSUE THREAD

**Issue by KamalAlipour** [BrightstarDB/BrightstarDB#253]
Hi,
I'm new in BrightstarDB. How can I insert just new triples into the embeded database by the RDF Client API or something else?
Thanks for your advice

Best regards
Kamal

**Comment by kal** [comment]
Through the API you basically have two options for adding triples:

1) Create a directory called import in the same directory that contains the database directory; add an RDF file in one of the supported syntaxes to that directory and then start an import job. See http://brightstardb.readthedocs.org/en/latest/RDF_Client_API/#data-imports

2) Add the triples in a transactional update - the syntax for your triples to add is simple NTriples/NQuads syntax. See http://brightstardb.readthedocs.org/en/latest/RDF_Client_API/#transactional-update

If you have the triples you want to create in memory then (2) is probably the easiest way to go. If you want a nicer syntax for creating the set of triples to add then I would recommend that you look through the dotNetRDF API as it has lots of good APIs for creating a graph of RDF triples which you can then serialize to a C# StringWriter in NQuads format - as BrightstarDB uses dotNetRDF, you already have the necessary assemblies available to do this. Take a look at https://bitbucket.org/dotnetrdf/dotnetrdf/wiki/User%20Guide for a good introduction to using dotNetRDF.

Cheers

Kal

**Comment by KamalAlipour** [comment]
Hi dear Kal,
Thank you so much for your respond but my problem is that the triples are recording more than one time when I use ExecuteTransaction more time with the same triples. I expect that BrightstarDB doesn't duplicate the triples and prevent to save duplicate triples but it doesn't.
I'm sorry for my english and hope you get my point.
Thanks for your advice

Kind regards
Kamal

**Comment by kal** [comment]
Hi Kamal,

Your English is great :)

If you are seeing duplicated triples in BrightstarDB then that is definitely a bug - however it really should not happen with truly duplicated *quads* - the same (subject, predicate, object, graph) cannot be inserted twice into the indexes so in theory there should be no way for a duplicate quad to be inserted. A duplicate triple could be inserted, but only if the triples are in different graphs.

However you should note that BrightstarDB will not treat an attempt to add a duplicate quad as an error - it will simply continue, ignoring the duplicates - so you won't get any feedback that duplicates have been ignored (this is by design - it should always be possible to import partially or completely duplicated data without having to deal with lots of messages / errors from BrightstarDB).

So, I think what you are seeing is just that BrightstarDB doesn't treat an attempt to upload duplicate triples/quads as an error - if so, then this is "by design" and not a bug. However, if when you read the triples back from BrightstarDB (e.g. in a SPARQL query or an export) you get duplicates of the same *quad* (including the graph part), then we have a problem :-) 
 
If you have a simple way to reproduce a condition where BrightstarDB produces duplicate quads, can you please share your code here? You can upload it as an attachment, or if you have it in a public GitHub repo, just let me know the URL for that repo.

Thanks,

Kal

**Comment by KamalAlipour** [comment]
Hi dear Kal,
It's my pleasure to talk to you :)
When I run the following code several times, the size of Data.bs, Transactions.bs and Master.bs files are increasing. 

var client = BrightstarService.GetClient("type=embedded;storesdirectory=D:\\Kamal;storename=Semantic");
IUriNode rdfType = schema.CreateUriNode(new Uri(NamespaceMapper.RDF + "type"));
INode seeAlsoSchema = schema.CreateUriNode(new Uri(NamespaceMapper.RDFS + "seeAlso"));
IUriNode dbPediaProperty = schema.CreateUriNode("wt:dbPedia");
string storeName="Semantic";
var data = new StringBuilder();
data.AppendLine("<" + dbPediaProperty + "> <" + rdfType + "> <" + seeAlsoSchema + "> .");
------------------------------------------------------------------------------------
client.ExecuteTransaction(storeName, null, null, data.ToString());
------------------------------------------------------------------------------------

but now I run the folowing paragraph instead of the last sentence, the size of Transactions.bs file just increases in the next runs.

if (client.DoesStoreExist(storeName))
            {
                var transactionData = new UpdateTransactionData
                {
                    NonexistencePreconditions = data.ToString(),
                    InsertData = data.ToString()
                };
                client.ExecuteTransaction(storeName, transactionData);
                
            }

Thanks for your advice

Your sincerely
Kamal

**Comment by kal** [comment]
Hi Kamal,

The data files will all increase in size, because even if nothing is added in a transaction, a page is created to record the entry points for that transaction in the database. The transactions.bs file is simply a record of what transactions have been submitted to the store (it is not a part of the database - it is there as a log / way to recover a store in the event of data corruption).

If you try exporting from the store (e.g. using Polaris) you should see that there are no duplicates in your data.

Cheers

Kal

**Comment by KamalAlipour** [comment]
Hi Kal,
It's great :)
Thank you so much.

Kind regards
Kamal
