### ISSUE TITLE
BrightstarDB.CodeGeneration.T4 Doesn't Work

### ISSUE THREAD

**Issue by cbfrank** [BrightstarDB/BrightstarDB#270]
HI
Thanks for the great work, I'm trying to use it with the Xamarin projects
After installed BrightstarDB.CodeGeneration.T4 1.13.0 on my Win10 laptop, I try to run the EntityContext.tt, but it failed.
I debugged it, and find there are some assembly reference issues.
I set break point in the function below:
`AppDomain.CurrentDomain.AssemblyResolve += (s, e) =>
    {
        var match = searchPaths.SelectMany( p => Directory.GetFiles(p, e.Name + ".dll", SearchOption.TopDirectoryOnly)).FirstOrDefault();
        if (match == null)
        {
            return null;
        }
        return Assembly.LoadFrom(match);
    };`
and find it's try to resolve the file: **System.Composition.TypedParts, Version=1.0.27.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a**
but in the folder **packages\BrightstarDB.CodeGeneration.1.13.0\tools**, the file **System.Composition.TypedParts.dll** is 1.0.30.0
Then I tried BrightstarDB.CodeGeneration.Console, which also doesn't work.. I debugged the code and in the "Generator.cs" Line 318, GetBrightstarAssemblyLocation, it try to find **BrightstarDB.dll** with hard code in the solution, but for the portable project and xamarin android project, there is no BrightstarDB.dll in the nugget package.

Thanks

**Comment by kal** [comment]
Thanks for the report. I'll need to take a look at this in a bit more detail, but it sounds like a couple of packaging issues for portable class library projects.

Just to double check - are you using Visual Studio or Xamarin Studio for these projects (it may not matter, but sometimes there can be differences between the two environments).

 In the short term, what you could do is create a .NET 4.6 application that shares the code from your PCL project and then try running the T4 template from there - not sure, but perhaps that would work around the portable library issues ?

I'm thinking that it may also make sense to package up the console code generator as a standalone console application so that there is always a way out of this.

**Comment by cbfrank** [comment]
Hi
Thank you for the fast reply.
I'm using Visual Studio with Xamarin, not Xamarin studio.
I tested your solution, and create a console project that targets 4.6 and it works!
At least I can generate the wrapper class now. 
By the way, I find the package BrightstarDB that contains a T4 template which doesn't use Roslyn to generate the code, this package works for me at least, but it has a bug, when an interface that marked with Entity is inherited from another interface which is not marked with Entity, the generated code is not correct.

Thanks

**Comment by kal** [comment]
Awesome, that also helps narrow things down a bit - there must be a bug in the portable packaging. I have also reproduced the error with using the Roslyn code generator here, so hopefully I can find some way to fix it!

I've opened #271 to track the issue with the pure-T4 code generator problem.

**Comment by cbfrank** [comment]
Great!. Thank you.

**Comment by kal** [comment]
Closed as this ticket has not been active for a long time and things will be moving on with the NETStandard builds.
