### ISSUE TITLE
Scalability / Clustering

### ISSUE THREAD

**Issue by smith64fx** [BrightstarDB/BrightstarDB#276]
Hey there,
First of all. Thank you for being open source! :-)

My question is: How scalable is your application? Is it possible to create clusters? And for commercial purposes is there still anything open source?

**Comment by kal** [comment]
You're most welcome ;-)

BrightstarDB 1.x doesn't do any form of clustering - it is something that I have on my list of "would like to have" for a 2.x release though and any sort of help in thinking about the implications of it and possible implementation approaches to scalable clustering would be welcome. I'm also keen to find ways to make use of Azure infrastructure as one possible approach to scaling.

On a single machine I tend to find that BrightstarDB performance starts to drop off when you get to somewhere between 10-50 million triples; but that is just a guideline, you may find that number moves either way by up to an order of magnitude depending on your application profile and your specific requirements. Improving performance on a single machine is right at the top of my priorities for the 2.x release.

Of course, that probably raises the question "so when is the 2.0 release then", to which the answer is umm...I don't yet know. I'm now also taking over development of our key dependency - dotNetRDF - so that inevitably means a slow down in the development of both projects and right now I'm in the process of (slowly) scoping out the work for dotNetRDF. Once I get a better sense of that hopefully I can start to pull together a roadmap for both dotNetRDF and BrightstarDB future developments.
