### ISSUE TITLE
Unable To Delete Binded EntityObjects

### ISSUE THREAD

**Issue by osc117** [BrightstarDB/BrightstarDB#288]
Hello,

My company uses BrightstarDB for some projects, and it's a great tool. But since beginning we have got a serious issue. When we use mvvm frameworks like MvvmLight or MvvmCross, deleting any BrightstardDB object that is binded is impossible and raise an InvalidOperationException :

> the event CollectionRemove must specify item position

I created a project reproducing the error (with MvvmLight) : 

https://drive.google.com/open?id=0B98ZSzSdzS7USDJjRHZlZm1mcnM

**Comment by kal** [comment]
Thanks for the report and the reproduction of the error.

It looks like the cause is the way that we invoke the CollectionChanged event. I've got a fix for it now which I'll try and package up as a 1.13.1 release today.

**Comment by osc117** [comment]
Thanks for the update ! 
I tired it, there are improvements on the reliability of deletion... but it still causes crashes.
Here is an evolution of my error reproduction project:
https://drive.google.com/open?id=0B98ZSzSdzS7UZEJ6R3JyVWpQeEU

**Comment by kal** [comment]
Ah! So this time the problem is that the deleted object isn't really in the loaded objects collection and the checking that the .NET framework is doing on the event args doesn't like -1 as the deleted object index. Really annoying X-(

So I have a workaround for this case that involves basically replacing the Remove event with a Reset event if the deleted entity is not in the loaded objects collection. It seems to work OK on your test application. 

Would it be possible for you to build from source and try it out in your full app please? I'd like to make sure that there are no other problems before I do another hotfix release!

The easiest way would be to just clone from `master` (not `develop` because that will involve updating all the other dependencies), build the BrightstarDB solution and then replace the assembly reference in your projects.

I'm not sure why the unit tests aren't picking this up though - perhaps I just don't have any tests with a subscriber to the event...which I probably should add!

**Comment by osc117** [comment]
Hi,

Thanks so much for the time you take to help us on this.
I could'nt get to start hotfix 1.13.2 version. Some crash would always occur in BrightstarDB.Client.ElbeddedBrightstarService constructor : 
` public EmbeddedBrightstarService(string baseLocation, EmbeddedServiceConfiguration serviceConfigurationOptions)
        {
           _serverCore = ServerCoreManager.GetServerCore(
               baseLocation,
               serviceConfigurationOptions ?? Configuration.EmbeddedServiceConfiguration);
        }
`
Because i never managed to get the right nugget package for dotNetRdf.

So i ended trying your modifications on the copy i had of the develop branch (likely 1.13.1) and everything worked fine !!! Thanks again !

**Comment by osc117** [comment]
Any idea of when the update will be avaible ? We are really looking for it to keep on wiith our projects ^^ 
Thanks again for you great work !

**Comment by kal** [comment]
I've just updated the packages on NuGet and on Codeplex.

Thanks for your help!

**Comment by osc117** [comment]
Hi it's me again ! 
Thanks for the update and your work ! I'm now able to delete objects....
But... (you gonna hate me on this) i'm still encountering crashes when deleting objects.

It seems that if i delete entities linked to other entities, everything is fine. But if i have some ICollection (like an ObservableCollection) of entities and that i delete them from the context, when doing a raise propertychanged on the collection a crash occurs. Giving a me a nullReferenceException on BirghtstarDB.EntityFramework.BrightstarEntityObject.GetHashCode()\r\n

I guess i could workaround this by creating a brightstar entity in charge of storing my collection. But i don't like so much the idea of having to create mostly useless entites just for any kind of entity i want to itterate through ^^

Here your can find my third iteration of my error reproduction project : 
https://drive.google.com/file/d/0B98ZSzSdzS7Ub2F1a1hOT09obDQ/view?usp=sharing

Oh and by the way, i believe there is some thread not being disposed somewhere because i oftenly have to restart VisualStudio when i try to start the app i got a file already in use exception (or i'm obviously missing something).

**Comment by kal** [comment]
Hi!

I was just going to write that you are probably missing a call to Shutdown() :-)

Can you start a separate issue in GitHub this delete bug please - it looks like it *might* be related to this issue, but its just better to track it as a separate issue. I would just do it myself, but its much better if the issue is started by you rather than by me then we can track where the useful bug reports are coming from ;-)

Cheers

Kal

**Comment by osc117** [comment]
Hi Kal !

Do you have any idea about when we can expect some updates with this issue ? Because here we still can't delete entites. Yet it's not stopping the development process, but as you can guess it would be enjoayble to know that we are able to use fully Brightstar on our projects.
Thanks again for your great work !

Cheers !

**Comment by kal** [comment]
Sorry - other work projects are taking priority right now. Hopefully I can sneak some time to take a look tomorrow.

**Comment by osc117** [comment]
UP ^^
