### ISSUE TITLE
Mvvm Crash when deleting Entities stored in ICollection in ViewModel

### ISSUE THREAD

**Issue by osc117** [BrightstarDB/BrightstarDB#290]
Hi
It seems that  if i have some ICollection (like an ObservableCollection) of entities and that i delete them from the context, when doing a raise propertychanged on the collection a crash occurs. Giving a me a nullReferenceException on BirghtstarDB.EntityFramework.BrightstarEntityObject.GetHashCode()\r\n

Here your can find my third iteration of my error reproduction project :
https://drive.google.com/file/d/0B98ZSzSdzS7Ub2F1a1hOT09obDQ/view?usp=sharing

Edit : 
I noticed that the crash occurs when my item is selected

**Comment by lenytu** [comment]
Hi Kal!
First, thanks for all your work! Brighstar is very awesome and helpful for our projects (I workd with osc117).
We are stuck by this issue. We developed a WPF application to enable user to visualize, add, modify or remove data from the DB. But, due to this issue, our WPF application does not enable users to delete items.  

Could you please tell us if there is any chance you work on this issue again? 
In case you do not envisage to work on this issue, do you have any workaround we could use?

Thank you for your help

**Comment by kal** [comment]
Hi,

I've pushed out a 1.13.3 release which I think will fix the issue for you.  Can you check it out and let me know if it helps.

Cheers

Kal

**Comment by lenytu** [comment]
Hi kal
Thank you very much for your help!!
 We will test this release and keep you informed.

**Comment by lenytu** [comment]
Hi Kal!!
Thank you so much! Your latest release fixes this issue.
However, it seems we have a similar issue when removing entities (without deleting) from bound collections. We will come back to you with a short sample in a few days.

Thanks again for the fix
Leny

**Comment by kal** [comment]
Closing this issue as there was a fix already released. @lenytu - if you have an example of the other error, please open a new issue for it, thanks!
