### ISSUE TITLE
Any() is not working

### ISSUE THREAD

**Issue by Beatles1692** [BrightstarDB/BrightstarDB#291]
I have a problem using Any in a scenario that I have posted [here](http://stackoverflow.com/questions/41086093/any-is-not-working-in-brightstardb).

**Comment by kal** [comment]
There are certain circumstances under which .Any() isn't supported due to the way the semantics (don't) map to the SPARQL ASK query semantics. However your example isn't one of those cases, and I have successfully reproduced your query in a working example. I've posted an answer on the SO question.

For reference, the full list of LINQ-to-SPARQL restrictions can be found [here](http://brightstardb.readthedocs.io/en/latest/Entity_Framework/#linq-restrictions).
