### ISSUE TITLE
Standalone .Net Standard 2.0 Target of BrightstarDB Building without Errors :)

### ISSUE THREAD

**Issue by dgerding** [BrightstarDB/BrightstarDB#306]
Hi,
This is not an issue.

I've "ported" the portable target of the BrightstarDB project to a .Net Standard 2.0 project and managed to get it to build without errors.  

KAL, is this of interest?  I'm assuming with a little more work it could be the baseline for a refresh of the project to support .net core 3 and beyond.  

I'd love to contribute my meager effort back to this project.  

Let me know and thanks.

Dave Gerding

**Comment by kal** [comment]
Hi @dgerding,

It would be really good to do a forward port of B* to .NETStandard 2 and/or .NET Core 3. Its been a while since I have worked on the code, so I suspect that it also could do with some updating of dependencies and a fresh look at the build process too. There is the question of what to do about NancyFX that I was using for the HTTP service as there has not been much movement in terms of getting a stable 2.0 release out for that project, so I was thinking that it might be that the better thing to do is to reimplement using ASP.NET Core instead.

I feel like we could potentially drop all of the old platforms now and just target .NET Standard 2 - AFAIK that still hits all of the original target platforms of B*, just requires slightly more modern baseline versions of them.

I'd be more than happy to take a look at any PR that gets us started on this work, and to hear your thoughts on supporting the older platforms.

Cheers

Kal

**Comment by dgerding** [comment]
Okay, did the pull request.  Hopefully that's a good start for a conversation.  

Dave

**Comment by kal** [comment]
Hi @dgerding 

I've merged my work into develop now. The core solution should build cleanly and targets NETStandard 1.6 and 2.0 as well as .NET Framework 4.5.1. There are some test failures to address still (I'm creating separate tickets for those) and the server components and moving to ASP.NET Core have not been addressed at all yet.

Would be great if you have time to take a look and see if it builds for you!

Cheers

Kal
