### ISSUE TITLE
Developer Build Compile Time Errors, Test Status

### ISSUE THREAD

**Issue by dgerding** [BrightstarDB/BrightstarDB#318]
Hi,
When I try and build the latest (src) solution I get compile-time errors (below).  I can't run the tests either, except for a tiny handful, because the errors are related to the compile time errors.

Are you going to release a build that you know passes the test suite you've got and maybe pushing that to Nuget?

All the platforms that I need B* runtime can use a .net standard 2.0 target.

Not sure how to get started with Brightstar right now because with the current build I can't seem to get anything to run right and am spooked by the lack of the tests running.

Any ideas?  

Thanks,
Dave G  

Error	NU1202	Package Microsoft.Build 16.0.461 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Microsoft.Build 16.0.461 supports:
  - net472 (.NETFramework,Version=v4.7.2)
  - netcoreapp2.1 (.NETCoreApp,Version=v2.1)	BrightstarDB.CodeGeneration.Console	C:\Users\david\source\repos\BrightstarDB\src\core\BrightstarDB.CodeGeneration.Console\BrightstarDB.CodeGeneration.Console.csproj	1	
Error	NU1202	Package Microsoft.CodeAnalysis.Workspaces.MSBuild 3.1.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Microsoft.CodeAnalysis.Workspaces.MSBuild 3.1.0 supports:
  - net472 (.NETFramework,Version=v4.7.2)
  - netcoreapp2.1 (.NETCoreApp,Version=v2.1)	BrightstarDB.CodeGeneration.Console	C:\Users\david\source\repos\BrightstarDB\src\core\BrightstarDB.CodeGeneration.Console\BrightstarDB.CodeGeneration.Console.csproj	1	
Error	NU1202	Package Moq 4.11.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Moq 4.11.0 supports:
  - net45 (.NETFramework,Version=v4.5)
  - netstandard2.0 (.NETStandard,Version=v2.0)	BrightstarDB.Tests	C:\Users\david\source\repos\BrightstarDB\src\core\BrightstarDB.Tests\BrightstarDB.Tests.csproj	1	
Error	NU1202	Package Moq 4.11.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Moq 4.11.0 supports:
  - net45 (.NETFramework,Version=v4.5)
  - netstandard2.0 (.NETStandard,Version=v2.0)	BrightstarDB.Tests	C:\Users\david\source\repos\BrightstarDB\src\core\BrightstarDB.Tests\BrightstarDB.Tests.csproj	1	
Error	NU1202	Package Moq 4.11.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Moq 4.11.0 supports:
  - net45 (.NETFramework,Version=v4.5)
  - netstandard2.0 (.NETStandard,Version=v2.0)	BrightstarDB.Tests	C:\Users\david\source\repos\BrightstarDB\src\core\BrightstarDB.Tests\BrightstarDB.Tests.csproj	1	
Error		Package restore failed. Rolling back package changes for 'BrightstarDB.CodeGeneration.Console'.

**Comment by dgerding** [comment]
Update... I got rid of those errors by removing the reference to netcoreapp1.0 in the BrightstarDB.Tests project.

**Comment by dgerding** [comment]
I'm getting 131 failed to 278 passed... which is why I'm concerned about using this latest build.  

I know you didn't use that last pull request... but is there some other way I can help?

**Comment by dgerding** [comment]
@kal Update: I've taken another pass at converting the existing to BrightstarDB project to .net standard 2.0, this time removing all the conditional compilation bits and related cruft code (200 little dorky edits).  I then made a new .net core 2.2 nunit test project and now there are only 25 tests failing.   

I'll probably do another pull request but we can chat first.  I'm hoping you're willing to lose the .net 4.5 compatibilities since moving to .net standard 2 still supports .net 461.

**Comment by kal** [comment]
Hi Dave,

There was a compile time error introduced by a minor version update to Moq in which they took out support for netstandard 1.0. It seems a bit strange to me that they would do that on a minor update but anyway the fix is to change the package reference to be fixed to 4.10.1 which was the last version that supported netstandard 1.0.

Once I do that I can compile everything in the core solution (src/core/core.sln) and run the tests across all platforms and I get:

netcoreapp 1.0 - 1221 / 1221 tests pass
netcoreapp 2.0&2.1 - 1305/1305 tests pass
.net451 - 1290/1290 tests pass

The netstandard 2 support is split across netcoreapp 2.0 and 2.1 because the code generation tests require netcoreapp2.1 (as you've noticed I think from those error messages you are seeing).

I'm going to look at modifying the projects and the appveyor build so that commits to the develop branch package up and release nuget pre-release packages, but for now if you have access to VS (I'm using 2017 still at the moment) then please try just building and running the tests in core.sln from inside VS, or take a look at the appveyor.yml and follow the same steps as are used in there to build the solution.

**Comment by dgerding** [comment]
Hi Kal,
Hmm.. maybe it's because I'm on VS2019.   I'll try the newest commit with the #319 fix and let you know.  

If you decide you want the version of the  BrightstartDB project with the target specific compiler directives (and non-standard 2 code snippets) removed let me know.  I left a comment breadcrumb where I removed anything edit but it was basically manual search and replace.  Single target .net standard 2.0 project. 

Thanks for the quick reply.

**Comment by dgerding** [comment]
Thanks! (see note in #319)
