### ISSUE TITLE
Possible documentation inconsistencies regarding persistence modes

### ISSUE THREAD

**Issue by Awsmolak** [BrightstarDB/BrightstarDB#326]
I was experimenting with changing store persistence types between append-only and rewritable. The documentation only mentions that there is a way to "truncate" the datastore. I assume tha this truncation process is actually referring to the `ConsolidateStore()` method. If so, it should probably be called out in that section of the documentation.

Also, if that truly is the case, the way the documentation reads leads one to assume that using `ConsolidateStore()` should not really be necessary with a database in rewritable mode. However, after doing a bunch of testing with some large rewritable datastores, it appears that consolidation does in-fact result in a drastically smaller data.bs file! (and much faster write execution) 

Unless I am doing something wrong, it seems to me that a larger emphasis should be placed on periodically running `ConsolidateStore()` regardless of the persistencetype setting.

(It could be possible that I had been creating append-only stores all along, but I did perform some ancillary testing that seemed to rule that out)

**Comment by kal** [comment]
Thanks for the comment!
It is true that consolidating a store that was created in rewriteable mode can reduce the store size a bit as the consolidation rewrites the resource and prefix indexes both of which may be compressed if you have deleted a lot of uniquely identified resources. The btree index pages might also get compressed a little bit if they are slightly unbalance (but below the threshold for a rebalance to take place).
I agree that it makes sense to update the docs so that it is clear that periodic consolidation will have an effect for both types of store (albeit a much stronger effect for the append-only store type).

**Comment by kal** [comment]
Updated docs in commit 74ca078
